### ISSUE TITLE
Wrong description in the Diagnostic Settings variable

### ISSUE THREAD

**Issue by luisarnauth** [Azure/terraform-azurerm-avm-res-cognitiveservices-account#22]
The description of the Diagnostic Settings variable mentions Key Vault when it should mention Cognitive Services Account.

https://github.com/Azure/terraform-azurerm-avm-res-cognitiveservices-account/blob/4a6ce673997b35e93966df43653766659514d43a/variables.tf#L146

**Comment by lonegunmanb** [comment]
@luisarnauth Thanks for reporting this issue to us! I'm working on a pr to fix it.
