### ISSUE TITLE
[AVM Module Issue]: diagnostic.tf

### ISSUE THREAD

**Issue by acauret** [Azure/terraform-azurerm-avm-res-cognitiveservices-account#48]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

This is incorrect:
name                           = coalesce(each.value.name != null, "diag-${var.name}") - This will either return true or false as coalesce takes any number of arguments and returns the first one that isn't null or an empty string.

should be 
name                           = coalesce(each.value.name , "diag-${var.name}")

+
"logAnalyticsDestinationType": null so terraform is always trying to set the logAnalyticsDestinationType

**Comment by lonegunmanb** [comment]
@acauret Thanks for reporting this bug to us! I'm working on a patch for it.
