### ISSUE TITLE
[AVM Module Issue]: logAnalyticsDestinationType is not set correctly for Diagnostic settings

### ISSUE THREAD

**Issue by acauret** [Azure/terraform-azurerm-avm-res-cognitiveservices-account#55]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

The logAnalyticsDestinationType should not be Dedicated but allow seeting of null value
![image](https://github.com/user-attachments/assets/0bcd8230-2e48-46b3-aa32-2f9bcd2e173d)

as everytime terrform runs it thinks there is a change.
![image](https://github.com/user-attachments/assets/99790a02-e5ab-45ff-a95b-49b1275952c0)

**Comment by lonegunmanb** [comment]
Thanks for opening this pr to us @acauret and sorry for the late reply, this diagnostic setting is required by [Azure Verified Module Specification](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#diagnostic-settings) so we won't fix it.

**Comment by tonyskidmore** [comment]
@lonegunmanb does this need more of a review?  The code below will always want to make changes on each run, which is certainly not ideal.  Setting the `azurerm_monitor_diagnostic_setting` outside of the module is the useable workaround.

````terraform

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "random_string" "example" {
  length  = 5
  special = false
  upper   = false
  lower   = true
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-openai-avm"
  location = "uksouth"
}

resource "azurerm_log_analytics_workspace" "law" {
  name                = "law-testing-${random_string.example.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

module "openai" {
  source  = "Azure/avm-res-cognitiveservices-account/azurerm"
  version = "0.3.0"

  kind                = "OpenAI"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  name                          = "oai-testing-${random_string.example.result}"
  sku_name                      = "S0"
  public_network_access_enabled = true

  diagnostic_settings = {
    sendToLogAnalytics = {
      name = "sendToLogAnalytics"
      workspace_resource_id = azurerm_log_analytics_workspace.law.id
    }
  }

  cognitive_deployments = {
    "gpt-35-turbo" = {
      name = "gpt-35-turbo"
      model = {
        format  = "OpenAI"
        name    = "gpt-35-turbo"
        version = "0301"
      }
      scale = {
        type = "Standard"
      }
    }
  }
}

````

**Comment by acauret** [comment]
@lonegunmanb - Please reopen this and fix - Just because its defined in the [Azure Verified Module Specification](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#diagnostic-settings) does not mean its correct. its very annoying as this happening on quite a few modules in AVM

This does not have the option for dedicated or azure diagnostics
![Image](https://github.com/user-attachments/assets/5f2e83ca-6ebb-407b-89ca-e5498f2b9862)

Azure Data factory does have this so it works correctly

![Image](https://github.com/user-attachments/assets/5c5a89ac-7128-4ed1-83ef-1d8768bcdd8d)
