### ISSUE TITLE
[AVM Module Issue]: add support for Azure Provider v4.0

### ISSUE THREAD

**Issue by chopeen** [Azure/terraform-azurerm-avm-res-cognitiveservices-account#61]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Modify the module to support `azurerm` v4 (see [4.0-upgrade-guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide) for change log and migration hints).

**Comment by chopeen** [comment]
Similar change implemented in another module: https://github.com/Azure/terraform-azurerm-avm-res-managedidentity-userassignedidentity/pull/53

**Comment by lonegunmanb** [comment]
@chopeen thanks for opening this request to us, I'll try to support `v4` very soon for this module.
