### ISSUE TITLE
[AVM Module Issue]: Add support for creating rai policies to use with cognitive deployments

### ISSUE THREAD

**Issue by seekerofsai** [Azure/terraform-azurerm-avm-res-cognitiveservices-account#76]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Cognitive LLM model deployments can refer to a RAI policy for content filtering and safety. 
This feature enables to create rai policies with policy json provided by the user, that can be used by Cognitive model deployments.

**Comment by lonegunmanb** [comment]
Will open a pr to support this feature.
